package ensemble

// EmbeddedModes contains the complete 80-mode reasoning taxonomy.
// Core-tier modes (~28) are the curated default set for UX.
// Advanced-tier modes (remaining) are accessible via --all or --tier flags.
//
// Mode codes follow the A-L category mapping:
//
//	A = Formal, B = Ampliative, C = Uncertainty, D = Vagueness,
//	E = Change, F = Causal, G = Practical, H = Strategic,
//	I = Dialectical, J = Modal, K = Domain, L = Meta
var EmbeddedModes = []ReasoningMode{
	// =========================================================================
	// A) Formal and mathematical reasoning (A1-A8)
	// =========================================================================
	{
		ID:             "deductive",
		Code:           "A1",
		Tier:           TierCore,
		Name:           "Deductive Inference",
		Category:       CategoryFormal,
		ShortDesc:      "Classical logical inference from premises to conclusions",
		Description:    "If the premises are true and the inference rules are valid, the conclusion must be true. Truth-preserving and typically monotonic.",
		Outputs:        "Valid entailments; proofs/derivations; contradictions/counterexamples",
		BestFor:        []string{"Spec checking", "Compliance logic", "Formal arguments", "Must/shall implications"},
		FailureModes:   []string{"Garbage-in (false premises)", "Missing premises that matter in reality"},
		Differentiator: "Truth-preserving: makes explicit what is already implicit in premises",
	},
	{
		ID:             "mathematical-proof",
		Code:           "A2",
		Tier:           TierCore,
		Name:           "Mathematical Proof",
		Category:       CategoryFormal,
		ShortDesc:      "Proof-theoretic reasoning with formal derivations",
		Description:    "Deduction where the proof object matters—what counts as a proof, how it is constructed. Emphasizes derivability and proof structure.",
		Outputs:        "Formal proofs (sometimes machine-checkable); proof transformations",
		BestFor:        []string{"Formal methods", "Theorem proving", "Certified reasoning pipelines"},
		FailureModes:   []string{"Proving the wrong theorem (spec mismatch)", "Proving something irrelevant to outcomes"},
		Differentiator: "More structured than everyday deduction; emphasizes derivability and proof structure",
	},
	{
		ID:             "formal-verification",
		Code:           "A3",
		Tier:           TierCore,
		Name:           "Formal Verification",
		Category:       CategoryFormal,
		ShortDesc:      "Constructive proofs that correspond to verified programs",
		Description:    "A proof of existence must provide a construction/witness. Proofs correspond to algorithms (proofs as programs). Stronger link between proved and computable.",
		Outputs:        "Proofs that correspond to algorithms; verified implementations",
		BestFor:        []string{"Verified software", "Protocol verification", "Constructive math", "Show me the witness"},
		FailureModes:   []string{"Over-constraining when classical reasoning is acceptable and simpler"},
		Differentiator: "Ensures proofs are constructive and correspond to executable programs",
	},
	{
		ID:             "equational",
		Code:           "A4",
		Tier:           TierAdvanced,
		Name:           "Equational Reasoning",
		Category:       CategoryFormal,
		ShortDesc:      "Transform expressions using equalities and rewrite rules",
		Description:    "Transform expressions using equalities and rewrite rules while preserving meaning. Deduction specialized to symbol manipulation.",
		Outputs:        "Equivalent forms; normal forms; simplifications; invariants",
		BestFor:        []string{"Refactoring", "Optimization proofs", "Dimensional reasoning", "Invariant manipulation"},
		FailureModes:   []string{"Unsound rewrite rules", "Implicit domain restrictions (division by zero, overflow)"},
		Differentiator: "Deduction specialized to symbol manipulation; the everyday workhorse in math/CS",
	},
	{
		ID:             "model-theoretic",
		Code:           "A5",
		Tier:           TierAdvanced,
		Name:           "Model-Theoretic Reasoning",
		Category:       CategoryFormal,
		ShortDesc:      "Reason by constructing models that satisfy a theory",
		Description:    "Reason by constructing/analyzing models that satisfy a theory. Instead of derive, build a world where it holds or does not.",
		Outputs:        "Satisfiable/unsatisfiable; countermodels; interpretations",
		BestFor:        []string{"Consistency checks", "Finding hidden assumptions", "Generating counterexamples"},
		FailureModes:   []string{"Model doesn't match the intended semantics of the real system"},
		Differentiator: "Complements proof-theory: builds worlds rather than deriving conclusions",
	},
	{
		ID:             "constraint-sat",
		Code:           "A6",
		Tier:           TierAdvanced,
		Name:           "Constraint Satisfaction",
		Category:       CategoryFormal,
		ShortDesc:      "Encode requirements as constraints and solve for assignments",
		Description:    "Encode requirements as constraints and solve for assignments that satisfy them (or prove none exist). Mode is solve-by-consistency.",
		Outputs:        "Satisfying assignments; unsat certificates; minimal unsat cores; counterexamples",
		BestFor:        []string{"Scheduling", "Configuration", "Verification", "Policy enforcement", "Feasibility checks"},
		FailureModes:   []string{"Poor encoding (missed constraints) leading to false confidence"},
		Differentiator: "Solve-by-consistency rather than argument-by-argument inference",
	},
	{
		ID:             "type-theoretic",
		Code:           "A7",
		Tier:           TierCore,
		Name:           "Type-Theoretic Reasoning",
		Category:       CategoryFormal,
		ShortDesc:      "Use types to enforce invariants and compositional guarantees",
		Description:    "Use types (including dependent/refinement types) to enforce invariants. Propositions as types in some systems. Reasoning integrated into construction.",
		Outputs:        "Type derivations; well-typed programs; compositional guarantees",
		BestFor:        []string{"API design", "Correctness-by-construction", "Safe composition of large systems"},
		FailureModes:   []string{"Fighting the type system instead of clarifying the spec it encodes"},
		Differentiator: "Reasoning is integrated into construction; great for modular correctness",
	},
	{
		ID:             "edge-case",
		Code:           "A8",
		Tier:           TierCore,
		Name:           "Edge Case Reasoning",
		Category:       CategoryFormal,
		ShortDesc:      "Find counterexamples by iterative abstraction refinement",
		Description:    "Propose an abstraction, check it, if a counterexample appears refine the abstraction and repeat. A loop blending deduction + model checking + refinement.",
		Outputs:        "Either a proof of property or a concrete counterexample; refined models",
		BestFor:        []string{"Verification", "Security properties", "Systems where full modeling is too expensive"},
		FailureModes:   []string{"Endless refinement loops if the abstraction boundary is poorly chosen"},
		Differentiator: "Iterative loop that scales verification through progressive refinement",
	},

	// =========================================================================
	// B) Ampliative reasoning (B1-B11)
	// =========================================================================
	{
		ID:             "inductive",
		Code:           "B1",
		Tier:           TierCore,
		Name:           "Inductive Generalization",
		Category:       CategoryAmpliative,
		ShortDesc:      "Infer general patterns from observations",
		Description:    "Infer general patterns from observations. Not truth-preserving; new data can overturn conclusions.",
		Outputs:        "General rules; trends; predictors",
		BestFor:        []string{"Learning from experience", "Pattern discovery", "Forming priors"},
		FailureModes:   []string{"Overgeneralizing from small/biased samples"},
		Differentiator: "Goes beyond premises to form general rules; the basis of empirical learning",
	},
	{
		ID:             "statistical",
		Code:           "B2",
		Tier:           TierAdvanced,
		Name:           "Statistical Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Frequentist inference from samples via estimators and tests",
		Description:    "Inference about populations from samples via estimators, confidence intervals, tests, error rates. Emphasizes long-run properties of procedures.",
		Outputs:        "Effect estimates + uncertainty tied to sampling procedures",
		BestFor:        []string{"A/B tests", "QA", "Inference under repeated-sampling assumptions"},
		FailureModes:   []string{"P-value worship", "Confusing no evidence with evidence of no effect"},
		Differentiator: "Avoids probability of hypotheses; emphasizes long-run procedure properties",
	},
	{
		ID:             "bayesian",
		Code:           "B3",
		Tier:           TierAdvanced,
		Name:           "Bayesian Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Update degrees of belief with evidence via Bayes' rule",
		Description:    "Represent degrees of belief as probabilities and update them with evidence. Probability as rational credence management.",
		Outputs:        "Posterior beliefs; predictive distributions; uncertainty-aware forecasts",
		BestFor:        []string{"Integrating prior knowledge + data", "Diagnosis", "Forecasting", "Online learning"},
		FailureModes:   []string{"Overconfident priors", "Making up priors without sensitivity analysis"},
		Differentiator: "Probability as rational credence management; coherence through Bayes' rule",
	},
	{
		ID:             "likelihood",
		Code:           "B4",
		Tier:           TierAdvanced,
		Name:           "Likelihood Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Compare hypotheses via how well they predict observed data",
		Description:    "Compare how well hypotheses predict observed data via likelihoods without necessarily committing to priors.",
		Outputs:        "Likelihood ratios; relative evidential support rankings",
		BestFor:        []string{"Model comparison", "Forensic evidence strength", "Hypothesis triage"},
		FailureModes:   []string{"Ignoring base rates/priors entirely when they matter for decisions"},
		Differentiator: "Separates data support from belief after priors; sits between Bayesian and frequentist",
	},
	{
		ID:             "option-generation",
		Code:           "B5",
		Tier:           TierCore,
		Name:           "Option Generation",
		Category:       CategoryAmpliative,
		ShortDesc:      "Abductive inference to generate best candidate explanations",
		Description:    "From observations, propose hypotheses that would best explain them. Introduces hidden mechanisms and causes. Not guaranteed but creative.",
		Outputs:        "Candidate explanations/models; best current story; generated options",
		BestFor:        []string{"Hypothesis generation", "Incident triage", "Diagnosis", "Discovery"},
		FailureModes:   []string{"Story bias (choosing most appealing explanation, not most supported)"},
		Differentiator: "Introduces hidden mechanisms/causes; creative generation of possibilities",
	},
	{
		ID:             "analogical",
		Code:           "B6",
		Tier:           TierCore,
		Name:           "Analogical Transfer",
		Category:       CategoryAmpliative,
		ShortDesc:      "Transfer relational structure from known to new domains",
		Description:    "Transfer relational structure from a known domain/case to a new one, often deeper than surface similarity.",
		Outputs:        "Candidate inferences; adapted solutions; conceptual models/metaphors",
		BestFor:        []string{"Innovation", "Design", "Teaching", "Cross-domain problem solving"},
		FailureModes:   []string{"False analogies (shared surface traits, different causal structure)"},
		Differentiator: "Particular-to-particular transfer; seeds abduction with structural parallels",
	},
	{
		ID:             "case-based",
		Code:           "B7",
		Tier:           TierAdvanced,
		Name:           "Case-Based Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Retrieve similar past cases and adapt their solutions",
		Description:    "Retrieve similar past cases and adapt their solutions. Emphasizes retrieval metrics + adaptation operators + case libraries.",
		Outputs:        "Proposed solutions justified by precedent; playbook actions",
		BestFor:        []string{"Precedent reasoning", "Customer support", "Clinical decision support", "Ops playbooks"},
		FailureModes:   []string{"Cargo-culting: applying precedent without checking context changes"},
		Differentiator: "More operational than analogy: emphasizes retrieval and adaptation mechanics",
	},
	{
		ID:             "conceptual-blending",
		Code:           "B8",
		Tier:           TierCore,
		Name:           "Conceptual Blending",
		Category:       CategoryAmpliative,
		ShortDesc:      "Combine explanations into generalized reusable strategies",
		Description:    "Use explanations of why solutions work to generalize reusable rules and plans. Generalizes like induction but guided by deductive explanation.",
		Outputs:        "Generalized strategies with explanatory justification; novel concept combinations",
		BestFor:        []string{"Turning expert solutions into SOPs", "Reducing overfitting to anecdotes", "Creative synthesis"},
		FailureModes:   []string{"Explanations that are internally elegant but empirically wrong"},
		Differentiator: "Induction guided and validated by deductive explanation; creativity through combination",
	},
	{
		ID:             "simplicity",
		Code:           "B9",
		Tier:           TierAdvanced,
		Name:           "Simplicity Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Prefer hypotheses with fewer assumptions (Occam, MDL)",
		Description:    "Prefer hypotheses that explain data with fewer assumptions or shorter descriptions, balancing fit vs complexity.",
		Outputs:        "Bias toward simpler models; complexity penalties; regularization choices",
		BestFor:        []string{"Model selection", "Avoiding overfitting", "Choosing parsimonious policies"},
		FailureModes:   []string{"Oversimplifying when the world is genuinely complex/nonlinear"},
		Differentiator: "Selection principle across hypotheses; often paired with abduction and statistics",
	},
	{
		ID:             "reference-class",
		Code:           "B10",
		Tier:           TierAdvanced,
		Name:           "Reference-Class Reasoning",
		Category:       CategoryAmpliative,
		ShortDesc:      "Predict by comparing to base rates of similar past cases",
		Description:    "Predict by comparing to a base rate distribution of similar past projects/cases. Designed to counter planning fallacy and inside-view optimism.",
		Outputs:        "Base-rate forecasts; adjustment factors",
		BestFor:        []string{"Project timelines", "Budgets", "Risk forecasting", "Portfolio-level planning"},
		FailureModes:   []string{"Choosing the wrong reference class (too broad or too narrow)"},
		Differentiator: "Inductive method specifically designed to counter planning fallacy",
	},
	{
		ID:             "fermi",
		Code:           "B11",
		Tier:           TierAdvanced,
		Name:           "Fermi Estimation",
		Category:       CategoryAmpliative,
		ShortDesc:      "Rough quantitative estimates via decomposition and bounding",
		Description:    "Rough quantitative estimates via decomposition and bounding. Aims for scale correctness rather than precision.",
		Outputs:        "Back-of-the-envelope estimates; upper/lower bounds; sensitivity drivers",
		BestFor:        []string{"Early feasibility", "Sanity checks", "Identifying dominant terms"},
		FailureModes:   []string{"Hidden unit mistakes or implicit assumptions left untested"},
		Differentiator: "Heuristic quantitative mode aiming for scale correctness, not precision",
	},

	// =========================================================================
	// C) Reasoning under uncertainty (C1-C5)
	// =========================================================================
	{
		ID:             "probabilistic-logic",
		Code:           "C1",
		Tier:           TierAdvanced,
		Name:           "Probabilistic Logic",
		Category:       CategoryUncertainty,
		ShortDesc:      "Blend logical structure with probabilistic uncertainty",
		Description:    "Blend logical structure (relations/rules/quantifiers) with probabilistic uncertainty. More expressive than plain Bayesian models for relational domains.",
		Outputs:        "Probabilistic inferences over structured worlds; uncertain rule consequences",
		BestFor:        []string{"Knowledge graphs with uncertainty", "Uncertain policies", "Relational prediction"},
		FailureModes:   []string{"Model soup: too expressive leading to hard validation and brittle inference"},
		Differentiator: "More expressive than plain Bayesian for relational domains",
	},
	{
		ID:             "imprecise-probability",
		Code:           "C2",
		Tier:           TierAdvanced,
		Name:           "Imprecise Probability",
		Category:       CategoryUncertainty,
		ShortDesc:      "Represent uncertainty with probability ranges when precision isn't justified",
		Description:    "Represent uncertainty with ranges of probabilities when precision is not justified. Separates unknown from unlikely.",
		Outputs:        "Bounds on beliefs and decisions; sensitivity analyses",
		BestFor:        []string{"High-stakes decisions with weak priors", "Governance/risk", "Robustness checks"},
		FailureModes:   []string{"Paralysis (ranges are wide so we can't decide) without decision rules"},
		Differentiator: "Less committal than a single prior/posterior; separates unknown from unlikely",
	},
	{
		ID:             "evidential",
		Code:           "C3",
		Tier:           TierAdvanced,
		Name:           "Evidential Reasoning",
		Category:       CategoryUncertainty,
		ShortDesc:      "Allocate belief mass to sets of possibilities (Dempster-Shafer)",
		Description:    "Allocate mass to sets of possibilities; combine evidence into belief/plausibility intervals.",
		Outputs:        "Belief + plausibility ranges; fused evidence from multiple sources",
		BestFor:        []string{"Multi-source fusion", "Ambiguous evidence", "Partial identification"},
		FailureModes:   []string{"Misusing combination rules when sources are not independent"},
		Differentiator: "Can represent partial support for sets more directly than standard probability",
	},
	{
		ID:             "maximum-entropy",
		Code:           "C4",
		Tier:           TierAdvanced,
		Name:           "Maximum-Entropy Reasoning",
		Category:       CategoryUncertainty,
		ShortDesc:      "Choose least-committal distributions satisfying known constraints",
		Description:    "Choose distributions satisfying known constraints while assuming as little else as possible. Least-committal completion.",
		Outputs:        "Principled default distributions; minimally committed priors under constraints",
		BestFor:        []string{"Baselines", "Priors under constraints", "Principled defaults in modeling"},
		FailureModes:   []string{"Constraints are wrong/underspecified; outputs look objective but are not"},
		Differentiator: "Least-committal completion rather than explanation",
	},
	{
		ID:             "qualitative-probability",
		Code:           "C5",
		Tier:           TierAdvanced,
		Name:           "Qualitative Probability",
		Category:       CategoryUncertainty,
		ShortDesc:      "Ordinal plausibility ranks instead of numeric probabilities",
		Description:    "Replace numeric probabilities with ordinal degree-of-disbelief ranks. Update by shifting ranks. Useful when only ordering is defensible.",
		Outputs:        "Ordered plausibility levels; belief dynamics without precise probabilities",
		BestFor:        []string{"Early-stage hypothesis ranking", "Reasoning with weak quantification"},
		FailureModes:   []string{"Losing important magnitude information when magnitude actually matters"},
		Differentiator: "More structured than defaults, less numeric than Bayes; ordering without magnitudes",
	},

	// =========================================================================
	// D) Reasoning under vagueness (D1-D5)
	// =========================================================================
	{
		ID:             "fuzzy",
		Code:           "D1",
		Tier:           TierAdvanced,
		Name:           "Fuzzy Reasoning",
		Category:       CategoryVagueness,
		ShortDesc:      "Truth as a degree for predicates with blurred boundaries",
		Description:    "Truth is a degree (0-1) because predicates have blurred boundaries. Fuzzy truth is not probability: it is graded applicability.",
		Outputs:        "Degrees of membership/truth; fuzzy rule outputs",
		BestFor:        []string{"Control systems", "Scoring/rubrics", "Policies with soft thresholds"},
		FailureModes:   []string{"Treating fuzzy scores like calibrated probabilities"},
		Differentiator: "Fuzzy membership is graded applicability, not uncertainty about crisp facts",
	},
	{
		ID:             "ambiguity-detection",
		Code:           "D2",
		Tier:           TierCore,
		Name:           "Ambiguity Detection",
		Category:       CategoryVagueness,
		ShortDesc:      "Identify unknown, undefined, and indeterminate states",
		Description:    "More than two truth values; explicitly represent unknown or undefined. Inferences that track indeterminacy rather than forcing a binary choice.",
		Outputs:        "Inferences tracking indeterminacy; identified ambiguities; clarification needs",
		BestFor:        []string{"Databases with nulls", "Partial specs", "Missingness-aware reasoning"},
		FailureModes:   []string{"Conflating unknown with false"},
		Differentiator: "Targets incompleteness and ambiguity; surfaces what is truly unknown",
	},
	{
		ID:             "rough-set",
		Code:           "D3",
		Tier:           TierAdvanced,
		Name:           "Rough Set Reasoning",
		Category:       CategoryVagueness,
		ShortDesc:      "Approximate concepts by definite-in vs possibly-in given features",
		Description:    "Approximate a concept by what is definitely in vs possibly in, given limited features/indiscernibility.",
		Outputs:        "Lower/upper bounds on classifications; boundary regions",
		BestFor:        []string{"Interpretability-focused classification", "Feature-limited domains"},
		FailureModes:   []string{"Overconfidence about what is definitely in/out when features are weak"},
		Differentiator: "Membership arises from granularity of observation, not degrees of truth",
	},
	{
		ID:             "prototype-reasoning",
		Code:           "D4",
		Tier:           TierCore,
		Name:           "Prototype Reasoning",
		Category:       CategoryVagueness,
		ShortDesc:      "Categorize by similarity to prototypes rather than strict definitions",
		Description:    "Categorize by similarity to prototypes/exemplars rather than strict necessary-and-sufficient definitions. Graded category judgments.",
		Outputs:        "Graded category judgments; typicality effects",
		BestFor:        []string{"UX taxonomies", "Product categorization", "Human-facing labeling"},
		FailureModes:   []string{"Hidden bias in prototypes", "Category drift over time"},
		Differentiator: "Natural for human categories; complements fuzzy/rough with similarity geometry",
	},
	{
		ID:             "qualitative",
		Code:           "D5",
		Tier:           TierAdvanced,
		Name:           "Qualitative Reasoning",
		Category:       CategoryVagueness,
		ShortDesc:      "Reason with signs and monotone influences, not exact numbers",
		Description:    "Reason with qualitative states (increasing, decreasing, positive influence) instead of exact numbers. Coarse modeling for robustness.",
		Outputs:        "Directional predictions; qualitative constraints; sanity checks",
		BestFor:        []string{"Early architecture", "Feedback reasoning", "Does this trend make sense checks"},
		FailureModes:   []string{"Missing nonlinear thresholds where sign reasoning breaks down"},
		Differentiator: "Not primarily uncertainty; coarse modeling for robustness and early design",
	},

	// =========================================================================
	// E) Reasoning with inconsistency, defaults, and change (E1-E7)
	// =========================================================================
	{
		ID:             "non-monotonic",
		Code:           "E1",
		Tier:           TierAdvanced,
		Name:           "Non-Monotonic Reasoning",
		Category:       CategoryChange,
		ShortDesc:      "Adding information can retract previous conclusions",
		Description:    "Adding information can retract previous conclusions. Most real knowledge bases are non-monotonic unlike classical deduction.",
		Outputs:        "Default conclusions with explicit revision behavior",
		BestFor:        []string{"Rule systems with exceptions", "Policies", "Normally-qualified knowledge"},
		FailureModes:   []string{"Unclear priority rules leading to inconsistent or surprising behavior"},
		Differentiator: "Classical deduction is monotonic; most real knowledge is not",
	},
	{
		ID:             "default-typicality",
		Code:           "E2",
		Tier:           TierAdvanced,
		Name:           "Default Reasoning",
		Category:       CategoryChange,
		ShortDesc:      "Use normally/typically rules overridden by more specific info",
		Description:    "Use normally/typically rules overridden by more specific info. Often categorical rather than numeric probabilities.",
		Outputs:        "Typical conclusions; exception handling",
		BestFor:        []string{"Ontologies", "Rule engines", "SOPs with carve-outs"},
		FailureModes:   []string{"Defaults become facts and stop being questioned"},
		Differentiator: "Categorical (default applies or not) rather than numeric probabilities",
	},
	{
		ID:             "defeasible",
		Code:           "E3",
		Tier:           TierAdvanced,
		Name:           "Defeasible Reasoning",
		Category:       CategoryChange,
		ShortDesc:      "Tentative conclusions that can be defeated by counterevidence",
		Description:    "Conclusions can be defeated by counterevidence or stronger rules. Tracks priorities and strength of support.",
		Outputs:        "Warranted conclusions given competing reasons",
		BestFor:        []string{"Compliance/policy", "Medical guidelines", "Conflicting requirements"},
		FailureModes:   []string{"Priority schemes that encode politics rather than relevance"},
		Differentiator: "More explicit about conflict resolution than plain defaults",
	},
	{
		ID:             "belief-revision",
		Code:           "E4",
		Tier:           TierAdvanced,
		Name:           "Belief Revision",
		Category:       CategoryChange,
		ShortDesc:      "Revise accepted belief sets with new info (AGM-style)",
		Description:    "Principles for revising an accepted belief set with new info, especially when inconsistent. Minimal-change goals.",
		Outputs:        "Revised belief sets with minimal-change goals",
		BestFor:        []string{"Knowledge management", "Requirements evolution", "Source reconciliation"},
		FailureModes:   []string{"Minimal change preserves outdated core assumptions"},
		Differentiator: "Revises acceptance of propositions (vs Bayesian which revises degrees)",
	},
	{
		ID:             "paraconsistent",
		Code:           "E5",
		Tier:           TierAdvanced,
		Name:           "Paraconsistent Reasoning",
		Category:       CategoryChange,
		ShortDesc:      "Reason despite contradictions without explosion",
		Description:    "Tolerate contradictions without explosion (deriving everything). Contains inconsistency instead of immediately repairing it.",
		Outputs:        "Controlled inferences from inconsistent data",
		BestFor:        []string{"Merging inconsistent sources", "Messy enterprise data", "Early incident response"},
		FailureModes:   []string{"Never resolving contradictions that actually matter for action"},
		Differentiator: "Contains contradictions instead of immediately repairing them",
	},
	{
		ID:             "argument-mapping",
		Code:           "E6",
		Tier:           TierCore,
		Name:           "Argument Mapping",
		Category:       CategoryChange,
		ShortDesc:      "Build and evaluate structured pro/con argument networks",
		Description:    "Build arguments and counterarguments; compute which claims stand given attack/defense relations. Evaluate competing reasons.",
		Outputs:        "Accepted/warranted claims; rationale maps; argument structures",
		BestFor:        []string{"Governance", "Policy disputes", "Legal-style reasoning", "Stakeholder conflicts"},
		FailureModes:   []string{"Mistaking won the debate for is true (argument strength vs reality)"},
		Differentiator: "Not just derive consequences but evaluate competing reasons systematically",
	},
	{
		ID:             "assurance-case",
		Code:           "E7",
		Tier:           TierAdvanced,
		Name:           "Assurance Case Reasoning",
		Category:       CategoryChange,
		ShortDesc:      "Structured arguments for system safety/security with evidence",
		Description:    "Structured argument that a system is acceptably safe/secure/reliable, supported by evidence and subclaims. Bridges formal and empirical reasoning.",
		Outputs:        "Safety cases; risk arguments; evidence traceability",
		BestFor:        []string{"Safety-critical systems", "Compliance audits", "AI governance documentation"},
		FailureModes:   []string{"Paper compliance (beautiful argument, weak evidence)"},
		Differentiator: "Argumentation constrained by standards and evidence requirements",
	},

	// =========================================================================
	// F) Causal, counterfactual, and dynamic reasoning (F1-F7)
	// =========================================================================
	{
		ID:             "causal-inference",
		Code:           "F1",
		Tier:           TierAdvanced,
		Name:           "Causal Inference",
		Category:       CategoryCausal,
		ShortDesc:      "Identify causal relations and predict intervention effects",
		Description:    "Identify causal relations and predict effects of interventions. Distinguish P(Y|X) vs P(Y|do(X)). Correlation alone cannot resolve confounding.",
		Outputs:        "Causal effect estimates; intervention predictions; adjustment sets",
		BestFor:        []string{"Product impact", "Policy evaluation", "Root-cause analysis that guides action"},
		FailureModes:   []string{"Hidden confounders", "Unjustified causal assumptions"},
		Differentiator: "Distinguishes observation from intervention; encodes structural assumptions",
	},
	{
		ID:             "dependency-mapping",
		Code:           "F2",
		Tier:           TierCore,
		Name:           "Dependency Mapping",
		Category:       CategoryCausal,
		ShortDesc:      "Infer causal/dependency graph structure from data",
		Description:    "Infer causal graph structure from data + assumptions (and ideally interventions). Learn the dependency structure of a system.",
		Outputs:        "Candidate causal graphs; equivalence classes; hypotheses for experimentation",
		BestFor:        []string{"Early-stage domains with unclear mechanisms", "Prioritizing experiments", "System dependencies"},
		FailureModes:   []string{"Overtrusting discovery outputs without validating assumptions"},
		Differentiator: "Causal inference assumes structure; discovery/mapping tries to learn it",
	},
	{
		ID:             "counterfactual",
		Code:           "F3",
		Tier:           TierAdvanced,
		Name:           "Counterfactual Reasoning",
		Category:       CategoryCausal,
		ShortDesc:      "Evaluate alternate histories given a causal model",
		Description:    "Evaluate alternate histories given a causal model. What would have happened if a different action was taken.",
		Outputs:        "Counterfactual outcomes; blame/credit analyses; individualized explanations",
		BestFor:        []string{"Postmortems", "Accountability", "Scenario evaluation", "Personalized decisions"},
		FailureModes:   []string{"Confident counterfactuals from weak models"},
		Differentiator: "Needs causal structure beyond pure statistics to evaluate alternate histories",
	},
	{
		ID:             "failure-mode",
		Code:           "F4",
		Tier:           TierCore,
		Name:           "Failure Mode Analysis",
		Category:       CategoryCausal,
		ShortDesc:      "Explain and predict by identifying parts, interactions, and failures",
		Description:    "Explain/predict by identifying parts and interactions. Gives actionable intervention points and generalizes when mechanisms hold.",
		Outputs:        "Mechanistic explanations; levers; failure modes; intervention points",
		BestFor:        []string{"Engineering", "Debugging", "Safety analysis", "Reliability"},
		FailureModes:   []string{"Just-so mechanisms that sound plausible but are not validated"},
		Differentiator: "Stronger than correlation: gives actionable intervention points",
	},
	{
		ID:             "root-cause",
		Code:           "F5",
		Tier:           TierCore,
		Name:           "Root Cause Analysis",
		Category:       CategoryCausal,
		ShortDesc:      "Infer hidden faults/causes from symptoms using fault models",
		Description:    "Infer hidden faults/causes from symptoms using a fault/causal model plus uncertainty handling. Ranked causes and next-best tests.",
		Outputs:        "Ranked causes; next-best tests; triage plans",
		BestFor:        []string{"Incident response", "Troubleshooting", "Quality triage"},
		FailureModes:   []string{"Premature closure (locking onto one cause too early)"},
		Differentiator: "Abduction + Bayesian updates constrained by explicit fault models",
	},
	{
		ID:             "second-order-effects",
		Code:           "F6",
		Tier:           TierCore,
		Name:           "Second-Order Effects",
		Category:       CategoryCausal,
		ShortDesc:      "Run internal models to predict consequences under scenarios",
		Description:    "Run an internal model (mental or computational) to predict consequences under scenarios. What-if analysis and sensitivity.",
		Outputs:        "Scenario traces; sensitivity analyses; what-if results",
		BestFor:        []string{"Complex systems", "Policy design", "Engineering dynamics", "Capacity planning"},
		FailureModes:   []string{"Simulation overconfidence", "Unvalidated models"},
		Differentiator: "Generative prediction from a specified model; not proof-like",
	},
	{
		ID:             "systems-thinking",
		Code:           "F7",
		Tier:           TierCore,
		Name:           "Systems Thinking",
		Category:       CategoryCausal,
		ShortDesc:      "Reason about feedback loops, delays, and emergence",
		Description:    "Reason about interacting components over time: reinforcing/balancing loops, delays, unintended consequences. Explicitly multi-level and dynamic.",
		Outputs:        "Causal loop diagrams; leverage points; dynamic hypotheses",
		BestFor:        []string{"Org design", "Markets", "Reliability engineering", "Platform ecosystems"},
		FailureModes:   []string{"Vague loop stories without measurable hypotheses"},
		Differentiator: "Explicitly multi-level and dynamic; local linear reasoning often fails",
	},

	// =========================================================================
	// G) Practical reasoning (G1-G11)
	// =========================================================================
	{
		ID:             "means-end",
		Code:           "G1",
		Tier:           TierAdvanced,
		Name:           "Means-End Reasoning",
		Category:       CategoryPractical,
		ShortDesc:      "Derive actions/subgoals necessary to achieve goals",
		Description:    "From goals, derive actions/subgoals necessary or helpful to achieve them. About doing, not merely believing.",
		Outputs:        "Action rationales; subgoals; dependency chains",
		BestFor:        []string{"Strategy decomposition", "OKRs", "Operational planning"},
		FailureModes:   []string{"Local means become ends (process is the goal)"},
		Differentiator: "About doing, not merely believing; feeds planning and decision theory",
	},
	{
		ID:             "decision-under-uncertainty",
		Code:           "G2",
		Tier:           TierCore,
		Name:           "Decision Under Uncertainty",
		Category:       CategoryPractical,
		ShortDesc:      "Combine beliefs with utilities to choose actions",
		Description:    "Combine beliefs with preferences/utilities to choose actions. Option rankings and explicit tradeoffs via expected utility.",
		Outputs:        "Option rankings; policies; explicit tradeoffs",
		BestFor:        []string{"Portfolio choices", "Risk decisions", "Prioritization", "Pricing"},
		FailureModes:   []string{"Utility mismatch (optimizing what you don't truly value)"},
		Differentiator: "Adds values and consequences to belief updates; decision vs belief",
	},
	{
		ID:             "prioritization",
		Code:           "G3",
		Tier:           TierCore,
		Name:           "Prioritization",
		Category:       CategoryPractical,
		ShortDesc:      "Multi-criteria decision analysis with explicit tradeoffs",
		Description:    "Decide with multiple objectives (cost, speed, safety, equity) using weights, outranking, or Pareto frontiers. Makes tradeoffs explicit.",
		Outputs:        "Tradeoff surfaces; Pareto-efficient sets; transparent scoring models",
		BestFor:        []string{"Strategy", "Procurement", "Roadmap planning", "Governance"},
		FailureModes:   []string{"Arbitrary weights hiding politics", "False precision"},
		Differentiator: "Makes tradeoffs explicit instead of collapsing into one objective",
	},
	{
		ID:             "strategic-planning",
		Code:           "G4",
		Tier:           TierCore,
		Name:           "Strategic Planning",
		Category:       CategoryPractical,
		ShortDesc:      "Compute action sequences or policies achieving goals",
		Description:    "Compute action sequences or policies achieving goals under constraints and dynamics. Outputs procedures, not propositions.",
		Outputs:        "Plans; policies; contingencies; playbooks",
		BestFor:        []string{"Operations", "Project plans", "Incident response"},
		FailureModes:   []string{"Plans that ignore uncertainty and execution reality"},
		Differentiator: "Outputs a procedure, not a proposition; connects beliefs to action",
	},
	{
		ID:             "resource-allocation",
		Code:           "G5",
		Tier:           TierCore,
		Name:           "Resource Allocation",
		Category:       CategoryPractical,
		ShortDesc:      "Choose best solution relative to objective subject to constraints",
		Description:    "Choose the best solution relative to an objective subject to constraints. Not just feasible but optimal/near-optimal.",
		Outputs:        "Optimal/near-optimal decisions; tradeoff curves; shadow prices",
		BestFor:        []string{"Resource allocation", "Routing", "Scheduling", "Design tradeoffs"},
		FailureModes:   []string{"Optimizing the wrong objective or ignoring unmodeled constraints"},
		Differentiator: "Constraint satisfaction asks any feasible; optimization asks best feasible",
	},
	{
		ID:             "worst-case",
		Code:           "G6",
		Tier:           TierCore,
		Name:           "Worst-Case Analysis",
		Category:       CategoryPractical,
		ShortDesc:      "Choose actions that perform acceptably under worst conditions",
		Description:    "Choose actions that perform acceptably under worst plausible conditions or adversaries. Conservative policies and guarantees.",
		Outputs:        "Conservative policies; guarantees; buffer sizing; safety margins",
		BestFor:        []string{"Safety-critical systems", "Security", "Compliance", "Tail-risk control"},
		FailureModes:   []string{"Overconservatism (leaving too much value on the table)"},
		Differentiator: "Expected-value optimizes averages; robust optimizes guarantees",
	},
	{
		ID:             "minimax-regret",
		Code:           "G7",
		Tier:           TierAdvanced,
		Name:           "Minimax Regret",
		Category:       CategoryPractical,
		ShortDesc:      "Minimize worst-case regret from hindsight comparison",
		Description:    "Choose the action minimizing worst-case regret (difference from best action in hindsight). Hedged decisions under ambiguity.",
		Outputs:        "Regret-robust choices; hedged decisions",
		BestFor:        []string{"Strategy under deep uncertainty", "Irreversible decisions"},
		FailureModes:   []string{"Regret framing that ignores asymmetric catastrophic outcomes"},
		Differentiator: "More compromise-oriented than strict worst-case utility; useful under ambiguity",
	},
	{
		ID:             "satisficing",
		Code:           "G8",
		Tier:           TierAdvanced,
		Name:           "Satisficing",
		Category:       CategoryPractical,
		ShortDesc:      "Seek good-enough solutions given bounded resources",
		Description:    "Seek a solution that is good enough given time/compute/info limits rather than globally optimal. Rational under constraints.",
		Outputs:        "Thresholds; stopping rules; acceptable solutions",
		BestFor:        []string{"Real-time ops", "Fast-moving environments", "Early product strategy"},
		FailureModes:   []string{"Thresholds too low (chronic mediocrity) or too high (disguised optimization)"},
		Differentiator: "Not lazy optimization; rational decision-making under bounded resources",
	},
	{
		ID:             "value-of-information",
		Code:           "G9",
		Tier:           TierAdvanced,
		Name:           "Value-of-Information",
		Category:       CategoryPractical,
		ShortDesc:      "Decide which measurements reduce uncertainty most per cost",
		Description:    "Decide which measurements/experiments reduce uncertainty most per cost to improve decisions. Meta-decision theory.",
		Outputs:        "Experiment priorities; instrumentation plans; next best question",
		BestFor:        []string{"R&D prioritization", "Analytics roadmaps", "Investigation sequencing"},
		FailureModes:   []string{"Measuring what is easy, not what changes decisions"},
		Differentiator: "Meta-decision theory: picks information acquisition actions",
	},
	{
		ID:             "heuristic",
		Code:           "G10",
		Tier:           TierAdvanced,
		Name:           "Heuristic Reasoning",
		Category:       CategoryPractical,
		ShortDesc:      "Fast rules of thumb that often work but may be biased",
		Description:    "Use simple rules that often work; fast but biased. Should be paired with checks and calibration.",
		Outputs:        "Quick decisions/inferences; prioritization shortcuts",
		BestFor:        []string{"Triage", "First drafts", "Guiding search"},
		FailureModes:   []string{"Heuristics become doctrine"},
		Differentiator: "Less principled but cheaper; a conscious tradeoff of rigor for speed",
	},
	{
		ID:             "search-based",
		Code:           "G11",
		Tier:           TierAdvanced,
		Name:           "Search-Based Reasoning",
		Category:       CategoryPractical,
		ShortDesc:      "Systematically explore possibilities with pruning and heuristics",
		Description:    "Systematically explore possibilities (tree search, dynamic programming) guided by heuristics and pruning.",
		Outputs:        "Candidate solutions; best-found solutions; sometimes optimality proofs",
		BestFor:        []string{"Large combinatorial spaces", "Automated reasoning", "Try-options problems"},
		FailureModes:   []string{"Search blowup without good heuristics/structure"},
		Differentiator: "Computational method that can realize planning, proof, or optimization",
	},

	// =========================================================================
	// H) Strategic and social reasoning (H1-H4)
	// =========================================================================
	{
		ID:             "game-theoretic",
		Code:           "H1",
		Tier:           TierAdvanced,
		Name:           "Game-Theoretic Reasoning",
		Category:       CategoryStrategic,
		ShortDesc:      "Reason when outcomes depend on others' choices",
		Description:    "Reason when outcomes depend on others' choices. Decision theory treats uncertainty as nature; game theory treats it as other optimizers.",
		Outputs:        "Strategies; incentive analyses; equilibrium reasoning",
		BestFor:        []string{"Negotiation", "Pricing competition", "Security", "Platform rules"},
		FailureModes:   []string{"Assuming rationality/common knowledge where it does not exist"},
		Differentiator: "Treats uncertainty as other optimizers rather than passive nature",
	},
	{
		ID:             "perspective-taking",
		Code:           "H2",
		Tier:           TierCore,
		Name:           "Perspective Taking",
		Category:       CategoryStrategic,
		ShortDesc:      "Infer beliefs, intentions, and knowledge states of others",
		Description:    "Infer beliefs, intentions, knowledge states of others (nested beliefs). Essential for collaboration and communication.",
		Outputs:        "Behavior predictions; communication strategies; coordination plans",
		BestFor:        []string{"Leadership", "UX", "Teamwork", "Threat modeling"},
		FailureModes:   []string{"Mind-reading with overconfidence", "Projecting your incentives onto others"},
		Differentiator: "Focuses on beliefs-about-beliefs; essential for collaboration",
	},
	{
		ID:             "negotiation",
		Code:           "H3",
		Tier:           TierAdvanced,
		Name:           "Negotiation Reasoning",
		Category:       CategoryStrategic,
		ShortDesc:      "Reason about acceptable agreements under asymmetric info",
		Description:    "Reason about acceptable agreements and coalition formation under constraints and asymmetric information.",
		Outputs:        "Offers; concessions; coalition structures; Pareto improvements",
		BestFor:        []string{"Partnerships", "Sales", "Cross-team alignment"},
		FailureModes:   []string{"Winning the negotiation but losing the relationship/long-term incentives"},
		Differentiator: "More process- and constraint-oriented than abstract equilibrium analysis",
	},
	{
		ID:             "mechanism-design",
		Code:           "H4",
		Tier:           TierAdvanced,
		Name:           "Mechanism Design",
		Category:       CategoryStrategic,
		ShortDesc:      "Design rules so self-interested behavior leads to desired outcomes",
		Description:    "Design rules so that self-interested behavior leads to desired outcomes. Align incentives by choosing rules to shape behavior.",
		Outputs:        "Policies; marketplaces; compensation plans; governance structures",
		BestFor:        []string{"Platforms", "Internal governance", "Moderation policies", "Compensation"},
		FailureModes:   []string{"Goodharting (metrics become targets and get gamed)"},
		Differentiator: "Reverse game theory: choose rules to shape behavior rather than predict it",
	},

	// =========================================================================
	// I) Dialectical, rhetorical, and interpretive reasoning (I1-I5)
	// =========================================================================
	{
		ID:             "dialectical",
		Code:           "I1",
		Tier:           TierAdvanced,
		Name:           "Dialectical Reasoning",
		Category:       CategoryDialectical,
		ShortDesc:      "Advance understanding through structured opposition",
		Description:    "Advance understanding through structured opposition: surface tensions, refine concepts, integrate perspectives. Thesis-antithesis-synthesis.",
		Outputs:        "Refined positions; conceptual synthesis; clarified distinctions",
		BestFor:        []string{"Strategy debates", "Assumptions audits", "Resolving conceptual confusion"},
		FailureModes:   []string{"Endless debate without convergence criteria"},
		Differentiator: "Uses tension to improve concepts and frames rather than just tolerating contradictions",
	},
	{
		ID:             "rhetorical",
		Code:           "I2",
		Tier:           TierAdvanced,
		Name:           "Rhetorical Reasoning",
		Category:       CategoryDialectical,
		ShortDesc:      "Reasoning aimed at belief-change considering audience/framing",
		Description:    "Reasoning aimed at belief-change and coordination, considering audience, framing, ethos/pathos/logos. About adoption, not just truth.",
		Outputs:        "Persuasive arguments; narratives; positioning",
		BestFor:        []string{"Change management", "Stakeholder alignment", "External communication"},
		FailureModes:   []string{"Manipulative persuasion that erodes trust and long-run effectiveness"},
		Differentiator: "Not primarily truth-preserving; about adoption, ideally constrained by truth",
	},
	{
		ID:             "hermeneutic",
		Code:           "I3",
		Tier:           TierAdvanced,
		Name:           "Hermeneutic Reasoning",
		Category:       CategoryDialectical,
		ShortDesc:      "Infer meaning and intent from language under ambiguity",
		Description:    "Infer meaning and intent from language, documents, norms, artifacts using context and interpretive canons.",
		Outputs:        "Interpretations; reconciled meanings; clarified definitions",
		BestFor:        []string{"Contracts", "Policy docs", "Requirements", "Qualitative feedback synthesis"},
		FailureModes:   []string{"Over-interpreting; reading intent that is not there"},
		Differentiator: "Emphasizes context and ambiguity management, not only formal entailment",
	},
	{
		ID:             "narrative",
		Code:           "I4",
		Tier:           TierAdvanced,
		Name:           "Narrative Reasoning",
		Category:       CategoryDialectical,
		ShortDesc:      "Build coherent time-ordered explanations connecting events",
		Description:    "Build coherent time-ordered explanations connecting events, motives, causes into a story supporting prediction and action.",
		Outputs:        "Postmortems; strategy narratives; scenario stories",
		BestFor:        []string{"Incident reports", "Executive communication", "Complex causal chains"},
		FailureModes:   []string{"Narrative closure crowding out alternative hypotheses"},
		Differentiator: "Integrates causal/abductive/rhetorical constraints; risk is over-coherence",
	},
	{
		ID:             "sensemaking",
		Code:           "I5",
		Tier:           TierAdvanced,
		Name:           "Sensemaking",
		Category:       CategoryDialectical,
		ShortDesc:      "Build frames that organize signals and priorities under ambiguity",
		Description:    "Decide what kind of situation is this—build frames that organize signals, priorities, and actions under ambiguity.",
		Outputs:        "Situation frames; working hypotheses; shared mental models",
		BestFor:        []string{"Crisis leadership", "Early-stage strategy", "Ambiguous competitive landscapes"},
		FailureModes:   []string{"Locking onto the wrong frame and reasoning flawlessly inside it"},
		Differentiator: "Precedes many other modes: selects what counts as relevant evidence",
	},

	// =========================================================================
	// J) Modal, temporal, spatial, and normative reasoning (J1-J4)
	// =========================================================================
	{
		ID:             "modal",
		Code:           "J1",
		Tier:           TierAdvanced,
		Name:           "Modal Reasoning",
		Category:       CategoryModal,
		ShortDesc:      "Reason with necessity, possibility, and knowledge operators",
		Description:    "Reason with necessarily, possibly, knows, and after-action operators. Makes distinctions explicit that classical logic cannot express.",
		Outputs:        "Claims about possibility spaces; knowledge states; action effects",
		BestFor:        []string{"Security (knowledge)", "Planning (actions)", "Reasoning about contingencies"},
		FailureModes:   []string{"Treating possible as likely or knowable"},
		Differentiator: "Makes distinctions explicit that classical logic cannot express cleanly",
	},
	{
		ID:             "deontic",
		Code:           "J2",
		Tier:           TierAdvanced,
		Name:           "Deontic Reasoning",
		Category:       CategoryModal,
		ShortDesc:      "Reason about obligation, permission, and prohibition",
		Description:    "Reason about what is permitted, required, or forbidden. Handle norm conflicts and exceptions. Normative: about ought, not is.",
		Outputs:        "Norm-consistent action sets; compliance interpretations",
		BestFor:        []string{"Compliance", "Policy", "Ethics constraints in systems"},
		FailureModes:   []string{"Inconsistent norms; ignoring priority/lexical ordering of duties"},
		Differentiator: "Normative: about ought, not is. Often non-monotonic due to exceptions",
	},
	{
		ID:             "temporal",
		Code:           "J3",
		Tier:           TierAdvanced,
		Name:           "Temporal Reasoning",
		Category:       CategoryModal,
		ShortDesc:      "Reason about ordering, duration, persistence, and change over time",
		Description:    "Reason about ordering, duration, persistence, and change over time. Truth depends on time; persistence defaults introduce non-monotonicity.",
		Outputs:        "Temporal constraints; timelines; persistence assumptions",
		BestFor:        []string{"Scheduling", "Planning", "Forensics", "Narrative validity"},
		FailureModes:   []string{"Hidden assumptions about persistence (it stays true unless...)"},
		Differentiator: "Truth depends on time; persistence defaults introduce non-monotonicity",
	},
	{
		ID:             "spatial",
		Code:           "J4",
		Tier:           TierAdvanced,
		Name:           "Spatial Reasoning",
		Category:       CategoryModal,
		ShortDesc:      "Reason using geometry, topology, and diagrammatic representations",
		Description:    "Reason using geometry/topology and often diagrams (containment, adjacency, flows). Uses representational affordances of diagrams.",
		Outputs:        "Spatial inferences; layouts; flow arguments",
		BestFor:        []string{"Architecture diagrams", "Supply chains", "UX", "Robotics"},
		FailureModes:   []string{"Diagram does not equal truth; pictures can hide missing constraints"},
		Differentiator: "Uses representational affordances of diagrams; more direct than symbolic propositions",
	},

	// =========================================================================
	// K) Domain-specific reasoning (K1-K7)
	// =========================================================================
	{
		ID:             "scientific",
		Code:           "K1",
		Tier:           TierAdvanced,
		Name:           "Scientific Reasoning",
		Category:       CategoryDomain,
		ShortDesc:      "Hypothetico-deductive cycle: abduce, deduce, test, revise",
		Description:    "A workflow: abduce hypotheses, deduce predictions, test (statistics), revise beliefs/theories. An integrated pipeline rather than a single rule.",
		Outputs:        "Models; predictions; experiments; updated beliefs",
		BestFor:        []string{"R&D", "Experimentation platforms", "Measurement culture"},
		FailureModes:   []string{"Confirmation bias", "Underpowered experiments", "Reporting bias"},
		Differentiator: "An integrated pipeline rather than a single inference rule",
	},
	{
		ID:             "test-plan",
		Code:           "K2",
		Tier:           TierCore,
		Name:           "Test Plan Mode",
		Category:       CategoryDomain,
		ShortDesc:      "Design experiments to identify effects reliably",
		Description:    "Choose interventions, measurements, and sampling to identify effects (randomization, controls, blocking, instrumentation). Reasoning about how to learn reliably.",
		Outputs:        "Experiment plans; power analyses; measurement strategies",
		BestFor:        []string{"A/B testing", "Causal learning", "Evaluation of interventions"},
		FailureModes:   []string{"Measuring proxies that do not capture the real outcome (Goodhart risk)"},
		Differentiator: "Reasoning about how to learn reliably, not just how to analyze after the fact",
	},
	{
		ID:             "engineering-design",
		Code:           "K3",
		Tier:           TierCore,
		Name:           "Engineering Design Reasoning",
		Category:       CategoryDomain,
		ShortDesc:      "Iterate from requirements to architectures with tradeoffs",
		Description:    "Iterate from requirements to architectures to prototypes with tradeoffs, constraints, and failure analyses. Multi-objective and constraint-laden.",
		Outputs:        "Designs; specs; tradeoff justifications; test plans",
		BestFor:        []string{"Product development", "Reliability", "Architecture decisions"},
		FailureModes:   []string{"Premature optimization or over-engineering", "Ignoring maintainability"},
		Differentiator: "Inherently multi-objective and constraint-laden; relies on simulation and safety margins",
	},
	{
		ID:             "compliance",
		Code:           "K4",
		Tier:           TierCore,
		Name:           "Compliance Lens",
		Category:       CategoryDomain,
		ShortDesc:      "Apply rules to facts, interpret texts, reason from precedents",
		Description:    "Apply rules to facts, interpret texts, reason from precedents. Uses burdens/standards of proof and adversarial argumentation.",
		Outputs:        "Legal positions; compliance interpretations; precedent-based arguments",
		BestFor:        []string{"Compliance", "Governance", "Dispute resolution"},
		FailureModes:   []string{"Treating legal compliance as sufficient for ethical legitimacy (or vice versa)"},
		Differentiator: "Mixes deduction, analogy, rhetoric under institutional constraints",
	},
	{
		ID:             "moral-ethical",
		Code:           "K5",
		Tier:           TierAdvanced,
		Name:           "Moral-Ethical Reasoning",
		Category:       CategoryDomain,
		ShortDesc:      "Reason about right/wrong and value tradeoffs",
		Description:    "Reason about right/wrong and value tradeoffs across frameworks: consequentialist, deontological, virtue, contractualist, care ethics.",
		Outputs:        "Value constraints; ethical justifications; tradeoff statements",
		BestFor:        []string{"AI governance", "Product harms", "Trust & safety", "People policy"},
		FailureModes:   []string{"Values laundering (it's ethical because it helps our goal) without principled constraints"},
		Differentiator: "Normative: cannot be reduced to facts alone, though must be informed by them",
	},
	{
		ID:             "historical-investigative",
		Code:           "K6",
		Tier:           TierAdvanced,
		Name:           "Historical-Investigative Reasoning",
		Category:       CategoryDomain,
		ShortDesc:      "Reconstruct events from incomplete sources with triangulation",
		Description:    "Reconstruct what happened from incomplete sources; triangulate evidence; assess credibility; compare hypotheses.",
		Outputs:        "Best-available reconstructions; source assessments; confidence statements",
		BestFor:        []string{"Audits", "Incident reconstruction", "Due diligence", "Fraud investigations"},
		FailureModes:   []string{"Overfitting to a compelling narrative", "Neglecting disconfirming evidence"},
		Differentiator: "Strong emphasis on provenance, bias, and alternative explanations under uncertainty",
	},
	{
		ID:             "clinical-operational",
		Code:           "K7",
		Tier:           TierAdvanced,
		Name:           "Clinical-Operational Reasoning",
		Category:       CategoryDomain,
		ShortDesc:      "Pattern recognition + mechanistic models under time pressure",
		Description:    "Blend pattern recognition (cases), mechanistic models, tests, triage, and risk constraints under time pressure. Optimized for time-critical, high-stakes diagnosis.",
		Outputs:        "Triage decisions; test sequences; interventions with safety checks",
		BestFor:        []string{"SRE/ops", "Support escalation", "Medical-style workflows"},
		FailureModes:   []string{"Skipping confirmatory tests", "Treating correlations as mechanisms"},
		Differentiator: "Real-world hybrid mode optimized for time-critical, high-stakes diagnosis",
	},

	// =========================================================================
	// L) Meta-level and reflective modes (L1-L6)
	// =========================================================================
	{
		ID:             "meta-cognitive",
		Code:           "L1",
		Tier:           TierCore,
		Name:           "Meta-cognitive Monitoring",
		Category:       CategoryMeta,
		ShortDesc:      "Decide how to reason: mode selection and effort allocation",
		Description:    "Decide how to reason: which mode to use, effort allocation, what uncertainties matter, when to stop. Second-order reasoning about inference.",
		Outputs:        "Deliberation policies; checklists; stopping rules",
		BestFor:        []string{"High-stakes decisions", "Avoiding over-analysis", "Building reliable processes"},
		FailureModes:   []string{"Meta-infinite regress (thinking about thinking forever)"},
		Differentiator: "Second-order: the object is your inference process and resource allocation",
	},
	{
		ID:             "calibration",
		Code:           "L2",
		Tier:           TierAdvanced,
		Name:           "Calibration Reasoning",
		Category:       CategoryMeta,
		ShortDesc:      "Track how reliable your beliefs are via scoring and backtesting",
		Description:    "Track how reliable your beliefs are (forecast scoring, error bars, backtesting). First-order is what is true; calibration is how good am I at knowing.",
		Outputs:        "Calibrated confidence; forecast accuracy metrics; improved priors",
		BestFor:        []string{"Forecasting culture", "Risk reviews", "Decision reviews"},
		FailureModes:   []string{"Confusing confidence with competence", "Never measuring accuracy"},
		Differentiator: "Second-order uncertainty: how good am I at knowing what is true",
	},
	{
		ID:             "reflective-equilibrium",
		Code:           "L3",
		Tier:           TierAdvanced,
		Name:           "Reflective Equilibrium",
		Category:       CategoryMeta,
		ShortDesc:      "Iteratively adjust principles and case judgments for coherence",
		Description:    "Iteratively adjust both principles and case judgments until they cohere. Not deduction from fixed axioms; principles and judgments co-evolve.",
		Outputs:        "Coherent principles + case decisions; updated policies/norms",
		BestFor:        []string{"Policy design", "Governance", "Value-laden decisions"},
		FailureModes:   []string{"Coherence achieved by quietly dropping hard cases"},
		Differentiator: "Principles and judgments co-evolve rather than deriving from fixed axioms",
	},
	{
		ID:             "transcendental",
		Code:           "L4",
		Tier:           TierAdvanced,
		Name:           "Transcendental Reasoning",
		Category:       CategoryMeta,
		ShortDesc:      "Infer necessary preconditions from accepted facts",
		Description:    "Start from an accepted fact and infer what must be true for it to be possible. Not empirical induction; reasons from possibility to enabling conditions.",
		Outputs:        "Necessary preconditions; architectural must-haves",
		BestFor:        []string{"Deep framework design", "Conceptual audits", "First-principles constraints"},
		FailureModes:   []string{"Mistaking necessary-for-my-model as necessary-in-reality"},
		Differentiator: "Reasons from possibility to enabling conditions; not empirical",
	},
	{
		ID:             "adversarial-review",
		Code:           "L5",
		Tier:           TierCore,
		Name:           "Adversarial Review",
		Category:       CategoryMeta,
		ShortDesc:      "Red-team: try to break arguments, systems, and assumptions",
		Description:    "Assume the role of an attacker/critic: try to break arguments, systems, incentives, and assumptions. Intentionally antagonistic to current plans.",
		Outputs:        "Failure modes; exploits; counterexamples; what-could-go-wrong maps",
		BestFor:        []string{"Security", "Safety", "Governance", "Strategy stress-testing"},
		FailureModes:   []string{"Cynicism theater (finding clever attacks without prioritizing real risk)"},
		Differentiator: "Intentionally antagonistic to your current plan; pairs with robust reasoning",
	},
	{
		ID:             "debiasing",
		Code:           "L6",
		Tier:           TierAdvanced,
		Name:           "Debiasing Reasoning",
		Category:       CategoryMeta,
		ShortDesc:      "Structured checks to reduce predictable judgment errors",
		Description:    "Structured checks to reduce predictable errors: base rates, alternative hypotheses, premortems, disconfirmation search. A discipline for constraining inference.",
		Outputs:        "Checklists; improved judgments; documented uncertainty",
		BestFor:        []string{"High-stakes decisions", "Leadership reviews", "Forecasting", "Postmortems"},
		FailureModes:   []string{"Ritualized checklists that are not actually used to change conclusions"},
		Differentiator: "Not a new inference rule; a discipline for selecting and constraining inference",
	},
}

// CatalogVersion is the version string for the embedded mode catalog.
const CatalogVersion = "1.0.0"

// DefaultCatalog returns the embedded mode catalog initialized and validated.
func DefaultCatalog() (*ModeCatalog, error) {
	return NewModeCatalog(EmbeddedModes, CatalogVersion)
}
