#!/usr/bin/env bash
#
# Generate Mermaid dependency graph from Beads tasks
#
# Usage: ./scripts/generate-task-graph.sh [--output FILE] [--format mermaid|dot] [--filter LABEL]
#
# Examples:
#   ./scripts/generate-task-graph.sh                                  # Generate Mermaid to docs/graphs/task-graph.mmd
#   ./scripts/generate-task-graph.sh --filter phase-4                 # Only Phase 4 tasks
#   ./scripts/generate-task-graph.sh --output my-graph.mmd            # Custom output
#

set -euo pipefail

# Defaults
OUTPUT_FILE="docs/graphs/task-graph.mmd"
FORMAT="mermaid"
FILTER=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --format)
            FORMAT="$2"
            shift 2
            ;;
        --filter)
            FILTER="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--output FILE] [--format mermaid|dot] [--filter LABEL]"
            exit 1
            ;;
    esac
done

# Create output directory
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Get tasks
if [[ -n "$FILTER" ]]; then
    TASKS=$(br search --label "$FILTER" --all --format json --limit 1000 "." 2>/dev/null || echo "[]")
else
    TASKS=$(br search --all --format json --limit 1000 "." 2>/dev/null || echo "[]")
fi

# Check if we have tasks
TASK_COUNT=$(echo "$TASKS" | jq 'length')
if [[ "$TASK_COUNT" -eq 0 ]]; then
    echo "No tasks found"
    exit 1
fi

# Generate Mermaid graph
if [[ "$FORMAT" == "mermaid" ]]; then
    {
        echo "graph TD"
        echo "  %% Generated by generate-task-graph.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        echo ""

        # Define nodes with status styling
        echo "$TASKS" | jq -r '.[] |
            "  \(.id)[\"\(.id): \((.title // "No title") | gsub("\""; "\\\""))\"]" +
            (if .status == "closed" then ":::completed"
             elif .status == "in_progress" then ":::inprogress"
             elif .status == "blocked" then ":::blocked"
             elif .status == "deferred" then ":::deferred"
             else ":::open" end)'

        echo ""

        # Define dependencies
        echo "$TASKS" | jq -r '.[] |
            select(.depends_on != null and (.depends_on | length > 0)) |
            .depends_on[] as $dep |
            "  \($dep) --> \(.id)"'

        echo ""

        # Style definitions
        echo "  classDef completed fill:#90EE90,stroke:#006400,stroke-width:2px"
        echo "  classDef inprogress fill:#FFD700,stroke:#FF8C00,stroke-width:2px"
        echo "  classDef blocked fill:#FFB6C1,stroke:#DC143C,stroke-width:2px"
        echo "  classDef deferred fill:#D3D3D3,stroke:#808080,stroke-width:2px"
        echo "  classDef open fill:#87CEEB,stroke:#4682B4,stroke-width:2px"
    } > "$OUTPUT_FILE"

    echo "Generated Mermaid graph: $OUTPUT_FILE"
    echo "Tasks: $TASK_COUNT"

elif [[ "$FORMAT" == "dot" ]]; then
    # Generate Graphviz DOT format
    {
        echo "digraph beads_tasks {"
        echo "  // Generated by generate-task-graph.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        echo "  rankdir=TB;"
        echo "  node [shape=box, style=filled];"
        echo ""

        # Define nodes
        echo "$TASKS" | jq -r '.[] |
            "  \"\(.id)\" [label=\"\(.id): \((.title // "No title") | gsub("\""; "\\\""))\", " +
            (if .status == "closed" then "fillcolor=lightgreen"
             elif .status == "in_progress" then "fillcolor=gold"
             elif .status == "blocked" then "fillcolor=lightpink"
             elif .status == "deferred" then "fillcolor=lightgray"
             else "fillcolor=lightblue" end) + "];"'

        echo ""

        # Define edges
        echo "$TASKS" | jq -r '.[] |
            select(.depends_on != null and (.depends_on | length > 0)) |
            .depends_on[] as $dep |
            "  \"\($dep)\" -> \"\(.id)\";"'

        echo "}"
    } > "$OUTPUT_FILE"

    echo "Generated DOT graph: $OUTPUT_FILE"
    echo "Tasks: $TASK_COUNT"
    echo "Convert to PNG: dot -Tpng $OUTPUT_FILE -o ${OUTPUT_FILE%.dot}.png"
else
    echo "Unknown format: $FORMAT"
    exit 1
fi

# Generate statistics
OPEN=$(echo "$TASKS" | jq '[.[] | select(.status == "open")] | length')
IN_PROGRESS=$(echo "$TASKS" | jq '[.[] | select(.status == "in_progress")] | length')
BLOCKED=$(echo "$TASKS" | jq '[.[] | select(.status == "blocked")] | length')
CLOSED=$(echo "$TASKS" | jq '[.[] | select(.status == "closed")] | length')
DEFERRED=$(echo "$TASKS" | jq '[.[] | select(.status == "deferred")] | length')

echo ""
echo "Task Statistics:"
echo "  Open: $OPEN"
echo "  In Progress: $IN_PROGRESS"
echo "  Blocked: $BLOCKED"
echo "  Closed: $CLOSED"
echo "  Deferred: $DEFERRED"
echo "  Total: $TASK_COUNT"
